config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  get    'login'   => 'sessions#new',      as: :login
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy',  as: :logout

  post 'test' => 'hooks#test'

  get  'taxes/get_defaults', to: 'taxes#get_defaults'

  resources :taxes, :templates, :series

  get "invoices/amounts"
  get "recurring_invoices/amounts"
  get "items/amount"

  resources :commons do
    post 'select_print_template', on: :member
  end
  resources :invoices do
    post 'bulk', on: :collection
    post 'select_print_template', on: :member
    get 'autocomplete', on: :collection
    get 'chart_data', on: :collection
    get 'send_email', on: :member
    get 'print', on: :member
  end

  resources :recurring_invoices do
    post 'generate', on: :collection
    delete 'remove', on: :collection
    get 'chart_data', on: :collection
  end

  resources :customers do
    get 'autocomplete', on: :collection
    resources :invoices, only: [:index]
    resources :recurring_invoices, only: [:index]
  end

  post 'templates/set_default', to: 'templates#set_default'
  post 'series/set_default', to: 'series#set_default'
  post 'taxes/set_default', to: 'taxes#set_default'

  get 'settings/global'
  put 'settings/global', to: 'settings#global_update'
  get 'settings/profile'
  put 'settings/profile', to: 'settings#profile_update'
  get 'settings/tags'
  put 'settings/tags', to: 'settings#tags_update'
  get 'settings/hooks'
  put 'settings/hooks', to: 'settings#hooks_update'
  get 'settings/api_token'
  post 'settings/api_token'

  namespace :api do
    namespace :v1 do
      get 'invoices/print_template/:id/invoice/:invoice_id', to: 'commons#print_template', as: :rendered_template
      get 'stats', to: 'invoices#stats'
      resources :taxes, :series, only: [:index, :create, :show, :update, :destroy], defaults: { format: :json}
      resources :customers, only: [:index, :create, :show, :update, :destroy], defaults: { format: :json} do
        resources :invoices, only: [:index] # for filtering
      end
      resources :payments, only: [:show, :update, :destroy], defaults: {format: :json}
      resources :items, only: [:show, :update, :destroy], defaults: {format: :json} do
        resources :taxes, only: [:index], defaults: { format: :json}
      end

      resources :invoices, only: [:index, :create, :show, :update, :destroy, :send_email], defaults: { format: :json} do
        get 'send_email', on: :member
        resources :items, :payments, only: [:index, :create]
      end

      get 'recurring_invoices/generate_invoices', to: 'recurring_invoices#generate_invoices'
      resources :recurring_invoices, only: [:index, :create, :show, :update, :destroy], defaults: { format: :json} do
        resources :items, only: [:index, :create]
      end
    end
  end

  localized do
    resources :invoices, :recurring_invoices, :customers, :settings
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  include MetaAttributes

  extend ModelCsv

  acts_as_paranoid
  has_many :invoices
  has_many :estimates
  has_many :recurring_invoices

  # Validation
  validate :valid_customer_identification
  validates_uniqueness_of :name,  scope: :identification

  # Behaviors
  acts_as_taggable

  before_destroy :check_invoices

  CSV_FIELDS = [
    "id", "name", "identification", "email", "contact_person",
    "invoicing_address", "shipping_address", "meta_attributes",
    "active"
  ]

  scope :with_terms, ->(terms) {
    return nil if terms.empty?
    where('name ILIKE :terms OR email ILIKE :terms OR identification ILIKE :terms', terms: '%' + terms + '%')
  }

  scope :only_active, ->(boolean = true) {
    return nil unless boolean
    where(active: true)
  }

  def total
    invoices.where(draft: false, failed: false).sum :gross_amount || 0
  end

  def paid
    invoices.where(draft: false, failed: false).sum :paid_amount || 0
  end

  def due
    total - paid
  end

  def to_s
    if name?
      name
    elsif identification?
      identification
    elsif email?
      email
    else
      'Customer'
    end
  end

  def to_jbuilder
    Jbuilder.new do |json|
      json.(self, *(attribute_names - ["name_slug", "deleted_at"]))
    end
  end

  # csv format
  def self.csv(results)
    csv_stream(results, self::CSV_FIELDS, results.meta_attributes_keys)
  end


private

  def check_invoices
    if self.total > self.paid
      errors[:base] << "This customer can't be deleted because it has unpaid invoices"
      throw(:abort)
    end
  end

  def self.ransackable_scopes(auth_object = nil)
    [:with_terms, :only_active]
  end

  def valid_customer_identification
    unless name? or identification?
      errors.add :base, "Name or identification is required."
    end
  end

end

app/controllers/api/v1/customers_controller.rb
class Api::V1::CustomersController < Api::V1::BaseController
  before_action :set_type
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @search = Customer.ransack(params[:q])
    @customers = @search.result.paginate(page: params[:page], per_page: 20)
    render json: @customers
  end

  def show
    @customer = Customer.find params[:id]
    render json: @customer
  end

  def create
    @customer = Customer.new customer_params
    if @customer.save
      # Check if there is any meta_attribute
      if params[:meta_attributes]
        @customer.set_meta_multi params[:meta_attributes]
      elsif params[:invoice] and params[:invoice][:meta_attributes]
        @customer.set_meta_multi params[:invoice][:meta_attributes]
      end
      render json: @customer, status: :created, location: api_v1_customer_url(@customer)
    else
      render json: @customer.errors, status: :unprocessable_entity
    end
  end

  def update
    if @customer.update customer_params
      # Check if there is any meta_attribute
      if params[:meta_attributes]
        @customer.set_meta_multi params[:meta_attributes]
      elsif params[:invoice] and params[:invoice][:meta_attributes]
        @customer.set_meta_multi params[:invoice][:meta_attributes]
      end
      render json: @customer, status: :ok, location: api_v1_customer_url(@customer)
    else
      render json: @customer.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @customer.destroy
      render json: { message: "Content deleted" }, status: :no_content
    else
      render json: @customer.errors, status: :unprocessable_entity
    end
  end

  private

  def set_customer
    @customer = Customer.find params[:id]
  end

  def customer_params
    res = ActiveModelSerializers::Deserialization.jsonapi_parse(params, {})
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  include MetaAttributesControllerMixin
  include ApplicationHelper

  before_action :set_type
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :set_tags, only: [:index, :new, :create, :edit, :update, :destroy]

  # GET /customers
  def index
    # To redirect to the index with the current search params
    set_redirect_address(request.original_fullpath, "customers")
    @search = Customer.ransack(params[:q])
    @search.sorts = 'id desc' if @search.sorts.empty?
    @customers = @search.result
    @customers = @customers.tagged_with(params[:tag_list]) if params[:tag_list].present?

    respond_to do |format|
      format.html do
        @customers = @customers.paginate(page: params[:page],
                                         per_page: 20)
        render :index, layout: 'infinite-scrolling'
      end
      format.csv do
        set_csv_headers('customers.csv')
        self.response_body = Customer.csv @customers
      end
    end
  end

  # GET /customers/1
  def show
    redirect_to action: :edit
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    set_meta @customer

    respond_to do |format|
      if @customer.save
        format.html { redirect_to redirect_address("customers"), notice: 'Customer was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        set_meta @customer
        # Redirect to index
        format.html { redirect_to redirect_address("customers"), notice: 'Customer was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    respond_to do |format|
      if @customer.destroy
        format.html { redirect_to redirect_address("customers"), notice: 'Customer was successfully destroyed.' }
      else
        format.html { render :edit }
      end
    end
  end

  # GET /customers/autocomplete.json
  # View to get the customer autocomplete feature editing invoices.
  def autocomplete
    @customers = Customer.order(:name).where("name ILIKE ? and active = ?", "%#{params[:term]}%", true)
    respond_to do |format|
      format.json
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :identification, :email, :contact_person,
                                       :invoicing_address, :shipping_address, :active, tag_list: [])
    end

    def set_tags
      @tags = tags_for('Customer')
    end
end

app/views/customers/_form.html.haml
= form_for(@customer) do |f|
  - if @customer.errors.any?
    #error_explanation
      %h2
        = pluralize(@customer.errors.count, "error")
        prohibited this customer from being saved:
      %ul
        - @customer.errors.full_messages.each do |message|
          %li= message

  .m-b-2
    %h1.m-b-0
      - if @customer.new_record?
        New Customer
      - else
        = @customer
    .checkbox
      %label
        = f.check_box :active
        This customer is active

    = render partial: 'customers/form_fields', locals: {f: f}

  %fieldset.m-b-2
    %legend.m-b-1 Tags
    = render partial: 'shared/tagging_field', locals: {f: f, instance: @customer}

  %fieldset.m-b-2
    %legend.m-b-1 Meta Attributes
    = render partial: 'shared/meta_form', locals: {f: f, instance: @customer}

app/views/customers/_form_fields.html.haml
.row
  .col-xs-12.col-xl-8
    .row
      .col-md-6
        .form-group
          = f.label :name
          = f.text_field :name, class: 'form-control'
      .col-md-6
        .form-group
          = f.label :identification
          = f.text_field :identification, class: 'form-control'

    .row
      .col-md-6
        .form-group
          = f.label :contact_person
          = f.text_field :contact_person, class: 'form-control'
      .col-md-6
        .form-group
          = f.label :email
          = f.email_field :email, class: 'form-control'

    .row
      .col-md-6
        .form-group
          = f.label :invoicing_address
          = f.text_area :invoicing_address, class: 'form-control autosize', "data-address": "invoice"
      .col-md-6
        .form-group
          = f.label :shipping_address
          = link_to t("form_fields.copy invoicing address"), "#", "id": "js-copy-address", "class": "label-small-link"
          = f.text_area :shipping_address, class: 'form-control autosize', "data-address": "shipping"

    - unless f.object_name == 'customer'
      .row
        .col-md-6
          .form-group
            = f.label :terms
            = f.text_area :terms, class: 'form-control autosize'
        .col-md-6
          .form-group
            = f.label :notes
            = f.text_area :notes, class: 'form-control autosize'

app/views/customers/_searchform__filters.html.haml
.row
  .col-xs-12.col-md-6
    .row
      .col-xs-12.col-sm-6
        .form-group
          = f.label :only_active, "Show only active users"
          = f.check_box :only_active

app/views/customers/edit.html.haml
= render 'form'

.action-buttons{"data-role": "action-buttons"}
  = link_to t("delete"), @customer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger float-xs-left no-margin'
  = link_to t("back"), :back, class: 'btn btn-secondary'
  %button.btn.btn-success{type: 'button', data: {role: 'submit-form', target: 'form'}}=t("save")

app/views/customers/index.html.haml
%h1=t("customers")
%div{data: {role: 'infinite-scroll'}}
  .table-responsive
    %table.table.table-hover.table-striped.table-bordered
      %thead
        %tr
          %th.no-wrap=t("customer name")
          %th.no-wrap=t("identification")
          %th.text-right=t("due")
          %th.text-right=t("total")
          %th.text-right
      %tbody{data: {role: 'infinite-content'}}
        - @customers.each_with_index do |customer, i|
          %tr{data: {href: edit_customer_path(customer), itemid: customer.id, page_start: i.zero?, page: @customers.current_page}}
            %td.no-wrap
              =link_to customer.name, edit_customer_path(customer)
            %td.no-wrap= customer.identification
            %td.text-right= customer.due > 0.0 ? display_money(customer.due) : ""
            %td.text-right= display_money customer.total
            %td.text-center{"data-no-href": ""}
              %a{class: "material-icons",
                 title: "See Invoices",
                 href: "#{customer_invoices_path(customer.id)}"} list
  .content-loading.hide{data: {role: 'infinite-status'}}
    .spinner

app/views/customers/new.html.haml
= render 'form'

.action-buttons{"data-role": "action-buttons"}
  = link_to t("back"), :back, class: 'btn btn-secondary'
  %button.btn.btn-success{type: 'button', data: {role: 'submit-form', target: 'form'}}=t("save")